### PR TITLE
Add: issue #119 implementation of test in CI and unit tests

### LINKED ISSUE #119: Implement test in CI.rs
- Attempts to test the build based on the path_repo field (cargo test)
- Returns test status
- False if no unit tests?
- Log the results to the file in the path_log field

### PR DESCRIPTION
**Pull request by marcusalstrom**
Adds implementation of test()
as well as its respective unit tests.
The unit tests use two very small rust programs located at tests/lib/.

Please have a look at the error handling. Should we rather just use unwrap() and expect()?

Closes #119

### CODE REVIEW

**Comment by marcusalstrom** [comment]
Just realized now that this implementation assumes that the logs directory already exists. Either I add this check to the code or we make sure the directory exists before calling it.

**Comment by mebn** [comment]
looks good, just a few notes:

I think it's better if `CI.path_log` points to a folder instead of a file. That way we can write both `test.log` and `build.log` depending on if we call `CI.test()` or `CI.build()`.

`log_to_file()` could create the folder specified in `CI.path_log` if it dosen't exists, so we don't have to push it, and then the unit tests could delete that folder when done as part of cleanup.

If `assert_eq!(ci.status.test_status, true);` fails then `std::fs::remove_file()` won't run and the temp files are left. The assert_eq could be moved to execute last.

**Comment by mebn** [comment]
Also add docs at the top of the file with `//! write something here` to write doc for a module.

**Comment by mebn** [comment]
we could do something like this to avoid a commitID field:

```rust
let ci = CI::new(
    format!("{}/commit-{}", REPO_PATH, github.get_commit_id()), // repo
    format!("{}/commit-{}", LOGS_PATH, github.get_commit_id()), // log
);
```

I'm thinking the logs can be stored in `REPO_PATH/commit-123/test.log` and `REPO_PATH/commit-123/build.log`. That would work really well with the frontend.

**Comment by marcusalstrom** [comment]
You mean `LOG_PATH/commit-123/test.log` and `LOG_PATH/commit-123/build.log`. Right?

**Comment by mebn** [comment]
oh right, yeah LOG_PATH

**Comment by marcusalstrom** [comment]
Think I fixed all the issues

**Comment by mebn** [comment]
looks good!

**Pull request merged**
