### PR TITLE
Add: issue #37 Adds a point class

### PR DESCRIPTION
**Pull request by Olilin1**
Added a class to represent a point in cartesian coordinates. Implements some functionality I feel is missing from the currently used classes. If this pull request is approved I will create and issue to refactor existing code to use this class instead.

Closes (#37)

### CODE REVIEW

**Comment by marcusalstrom** [comment]
Think we need a distance(Point other) method as well

**Comment by Olilin1** [comment]
> Think we need a distance(Point other) method as well

Added in latest commit

**Comment by Olilin1** [comment]
Added equals function

**Comment by marcusalstrom** [comment]
Do we want to replace our old Point and Point2D.double implementation with this everywhere and make sure all the same tests pass before we merge this?

**Comment by dj-sourbrough** [comment]
I agree that it can be a separate issue.

I think it would be good with an area method as well such as;
x.area(Point y, Point z)

As seen in LIC3, LIC10 (#31), LIC14 (#35)

Should we add that with this PR or make a new issue for that?

**Comment by marcusalstrom** [comment]
> I agree that it can be a separate issue.
> 
> I think it would be good with an area method as well such as; x.area(Point y, Point z)
> 
> As seen in LIC3, LIC10 (#31), LIC14 (#35)
> 
> Should we add that with this PR or make a new issue for that?

I currently have a GeometryUtils.java class in progress that currently only computes the angle between three points. I think we should add the area method there as well in the future as soon as I have pushed.

**Comment by Olilin1** [comment]
I agree with Marcus. Calculating the area of a polygon seems a bit outside the scope of a Point class.

**Comment by marcusalstrom** [comment]
This looks good and since it doesn't interfere with any other code at this point i'm just gonna go ahead and merge.

**Pull request merged**
