### PR TITLE
add lic 1

### LINKED ISSUE #22: Implement functionality LIC1
There exists at least one set of three consecutive data points that cannot all be contained
within or on a circle of radius RADIUS1.
(0 ≤ RADIUS1)

### PR DESCRIPTION
**Pull request by mebn**
I think the last two test cases were wrong so i fixed them. I think they are right now, but someone else can double check. 

Last test case: when 3 points can be contained within a circle with RADIUS1 we return false.

Closes #22

### CODE REVIEW

**Comment by marcusalstrom** [comment]
Yea, I realize now I switched the logic the wrong way around when I did the tests originally. However, testLIC1TrueOnBorder() should assert false right?

LIC1 states:
There exists at least one set of three consecutive data points that cannot all be contained
within or on a circle of radius RADIUS1.
(0 ≤ RADIUS1)

**Comment by marcusalstrom** [comment]
I think just switching the statement 
(r >= PARAMETERS.RADIUS1)
to 
(r > PARAMETERS.RADIUS1)

should fix it

**Comment by mebn** [comment]
yeah, i think you're right, i fixed it

**Comment by marcusalstrom** [comment]
Looks good

**Pull request merged**
