### PR TITLE
Add: issue #17 Adds unittests for LIC12

### PR DESCRIPTION
**Pull request by dj-sourbrough**
Closes #17

### CODE REVIEW

**Comment by marcusalstrom** [comment]
Pull request seems to refer to #17 but has also made changes in test_LIC2 and test_LIC10. Look into that

**Comment by Olilin1** [comment]
At this point, the new test should also be changed to use the new Point class, as otherwise it won't compile properly.

**Comment by dj-sourbrough** [comment]
@Olilin1 I've removed the changes to the other tests and implement the point class now if you want to merge and run your implementation against the tests

**Comment by marcusalstrom** [comment]
Looks good now

**Pull request merged**
