### PR TITLE
Doc: issue #97 added 'our way of working' in README

### LINKED ISSUE #97: Assessed and documented your way of working (Essence standard)
Property:  You have assessed and documented (in one paragraph) your way of working (p. 58 in the [Essence standard](https://www.omg.org/spec/Essence/1.2/PDF) v1.2) by evaluating the checklist on p. 60:
In what state are you in? Why? What are obstacles to reach the next state?

Assessment: The grader will read your statement and assess whether it corresponds to an honest and accurate self-evaluation.

### PR DESCRIPTION
**Pull request by mebn**
Please change/add if you disagree.

closes #97

### CODE REVIEW

**Comment by mebn** [comment]
There is some spelling errors i can fix before we merge this

**Comment by marcusalstrom** [comment]
Here are some more things we can mention:
Test-driven development: we implemented testing before functionality. We made sure the one that created the test did not also develop the functionality. 
Every change/pull request had to be reviewed by another member. This helped us catch bugs before deployment.

**Comment by marcusalstrom** [comment]
Maybe also mention some things we could've improved such as using maven to better structure our code?

**Comment by mebn** [comment]
Yeah that's good to have, i've added that and fixed the spelling

**Pull request merged**
